# -*- coding: utf-8 -*-
"""ml_1_gyakorlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypCE-iah7WUTK_LteCulvWbbe25_BXuY

# Gyakorló feladatok megoldása

Egy string 3 leggyakoribb szavának kilistázás
"""

s = 'a a alma körte b b alma alma c d e f g haha haha'
f={}
for w in s.split():
  if w in f:
    f[w] += 1
  else:
    f[w] = 1
# az f szótárat érték szerint (key=f.get) rendezzük csökkenő sorrendbe (reversre=True)
# majd kérem az eredmény lista első három elemét
sorted(f, key=f.get, reverse=True)[:3]

"""Másik megoldás:"""

from collections import Counter #pythonban mindenre van külső csomag :)

x = Counter(s.split())
print(sorted(x, key=x.get, reverse=True)[:5])