# -*- coding: utf-8 -*-
"""ml_2_gyakorlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-BxP89xxeceL3q2bAPndPfZOr6ZCaOV

# Gyakorló feladatok
1. Dohányzik a két legidősebb ember?
"""

# adattábla betöltése
import pandas as pd
df = pd.read_csv("https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/MASS/survey.csv")

# 3 legidősebb ember életkora
sorted(df.Age)[-3:] # az Age oszlopot sorba rendezzük (eredménye lista), és kérem a 3 utolsó elemet

# a két legidősebb ember 70 év feletti, kérem az ő dohányzási változójukat
df.loc[df.Age>70,'Smoke']

"""Ez a megoldási mód jól példázza az adatelemzés és szoftverfejlesztés közti különbséget. Két egyszerű, egymásra épülő lekérdezéssel meg tudtuk válaszolni a konkrét kérdést, nem fejlesztettünk általános szoftvert...

2. Mi az átlagos Wr.Hnd a férfiaknál?
"""

# Először leszűrjük a férfiak feltételes résztömbjét, majd kérjük annak Wr.Hnd oszlopát. Ennek a Series-nek számoljuk az átlagát.
df[df.Sex=='Male']['Wr.Hnd'].mean()