# -*- coding: utf-8 -*-
"""MLjavitozh_20221215.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gn8XZ0jyrJNJcU1DeAVQY7BP-144Nwe4

# 1. feladat

Az https://archive.ics.uci.edu/ml/machine-learning-databases/00272/SkillCraft1_Dataset.csv adatbázis StarCraft2 játékosok statisztikáit tartalmazza. Kérdés, hogy ezekből az adatokból mennyire jelezhető előre, hogy melyik ligában játszik a játékos.

Hajts végre regressziós gépi tanulási kísérletet a `LeagueIndex` célváltozón (1-8 intervallum), úgy hogy a `GameID > 7000` játékosokat használod kiértékelő adatbázisnak.

Vigyázz! Az adatbázisban `?` jelöli a hiányzó értékeket.
"""

import pandas as pd
# töltsük be az adatbázist
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00272/SkillCraft1_Dataset.csv",na_values="?")
df.head() # nézzünk rá!

df.describe()
df[df.GameID > 7000].shape #kiértékelő adathalmaz mérete

df=df.dropna() #mivel vannak NAN értékek az adatbázisban, most kidobjuk őket, hogy ne okozzanak gondot később
df.shape #az egész adatbázis mérete

features = df.loc[:,"Age":]
df.loc[:,"Age":] # jellemzők az Age változó szerint

# szétválasztjuk a tanító- és teszthalmazokat, különvéve a jellemzőket és az osztálycímkét
trainFeatures = df[df.GameID <= 7000].loc[:,"Age":] # A 7000-nél kisebb egyenlőek Age szerint, tanító adatbázis része
trainLabels = df[df.GameID <= 7000].LeagueIndex # A 7000-nél kisebb egyenlőek osztálycímke(LeagueIndex) szerint, tanító adatbázis része
testFeatures = df[df.GameID > 7000].loc[:,"Age":] # A 7000-nél nagyobbak Age szerint a kiértékelő adatbázison
testLabels =  df[df.GameID > 7000].LeagueIndex # A 7000-nél nagyobbak a célváltozó szerint a kiértékelő adatbázison

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(min_samples_leaf=50) #DecisionTreeRegressor (azaz döntési fa regresszióra) használata
dt.fit(trainFeatures, trainLabels) # tanítás a tanító adatbázison
prediction = dt.predict(testFeatures) # predikció a kiértékelő adatbázison

from sklearn.metrics import mean_squared_error # MSE (RMSE végső gyökvonás nélkül)
mean_squared_error(prediction, testLabels) #MSE meghatározása

from sklearn.dummy import DummyRegressor
dummy = DummyRegressor(strategy='mean') # tanító adatbázis címkéinek átlaga lesz mindig a predikció
dummy.fit(trainFeatures, trainLabels)
mean_squared_error(dummy.predict(testFeatures), testLabels)

"""# 2. feladat
Melyik jellemző a legfontosabb a regressziós modellben?

Építs erre az egy jellemzőre egy döntési modellt (akár kézzel szabály-alapon, akár gépi tanulva)!
"""

dt = DecisionTreeRegressor(max_depth=1)

dt.fit(trainFeatures, trainLabels) # tanítás a tanító adatbázison

root = dt.tree_.feature[0] # gyökércsúcsban lévő feature indexe
trainFeatures.columns[root] # a legfontosabb jellemző kinyerése

root = dt.tree_.feature[0] # gyökércsúcsban lévő feature indexe
trainFeatures.columns[root] # a legfontosabb jellemző kinyerése

prediction = dt.predict(testFeatures) # predikció a kiértékelő adathalmazon
mean_squared_error(prediction, testLabels)

"""# 3. feladat
Próbálj ki egy másik regressziós algoritmust is az 1. feladatra. Mindkét módszernek hangold be a meta-paraméterit. (bónus feladat: a meta-paraméter értékekre a túltanási ábra kirajzolása)

A végén szövegként írd le, hogy a két algoritmus közül melyik a jobb!

"""

